Have LOCAL_PORTS override anything obtained from docker
nhumrich/small-prox pull request #2
Opened 2017-12-14 22:40 UTC by mackeyja92

2017-12-15 16:42 UTC, nhumrich commented on smallprox/mapper.py
> +async def update_local_overrides(config: dict):
This doesnt need to be `async`

2017-12-16 20:49 UTC, nhumrich requested changes

2017-12-16 20:49 UTC, nhumrich commented on smallprox/mapper.py
> +async def update_local_overrides(config: dict):
This doesnt need to be `async`

2017-12-16 21:10 UTC, mackeyja92 commented on smallprox/mapper.py
> +async def update_local_overrides(config: dict):
resolved

2017-12-18 18:12 UTC, nhumrich approved these changes
🐙

2017-12-18 18:12 UTC, merged